### ISSUE TITLE
Why naught launchs my script in debug mode?

### ISSUE THREAD

**Issue by axln** [andrewrk/naught#80]
Configured my project to use naught. Everything works fine.

But I don't understand why naught launch my app in debug mode. I run `ps` and see that my script is launched with the --debug-port option:

```
 /usr/bin/nodejs --debug-port=5859 /path/to/my/script.js
```

**Comment by RNELord** [comment]
This happens if you're using node 0.12. They've made changes to the cluster module. It's not actually listening with the debugger enabled, but if you send the SIGUSR1 it'll start the debugger and start listening on the specified port. Previously all workers would try bind on the same port.

See https://github.com/nodejs/node/blob/v0.12.7-release/lib/cluster.js#L318

**Comment by axln** [comment]
Ok, got it. So it has nothing to do with naught.
Thank you for the reply!
